[project]
name = 'pre-simplified-fees'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.aibtc-dao-traits-v2]
path = 'contracts/aibtc-dao-traits-v2.clar'
clarity_version = 2
epoch = 2.5

[contracts.faktory-dex-trait-v1-1]
path = 'contracts/faktory-dex-trait-v1-1.clar'
clarity_version = 2
epoch = 2.5

[contracts.faktory-trait-v1]
path = 'contracts/faktory-trait-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.main-dex]
path = 'contracts/main-dex.clar'
clarity_version = 2
epoch = 2.5

[contracts.name-faktory]
path = 'contracts/name-faktory.clar'
clarity_version = 2
epoch = 2.5

[contracts.name-faktory-dex]
path = 'contracts/name-faktory-dex.clar'
clarity_version = 2
epoch = 2.5

[contracts.name-pre-faktory]
path = 'contracts/name-pre-faktory.clar'
clarity_version = 2
epoch = 2.5

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
